const body=document.querySelector('body')
const play=document.createElement('div')
body.appendChild(div)
const button=document.createElement('button')
play.classList.add('play')
play.setAttribute('')
div.appendChild('button')
const a=document.createElement('a')
button.appendChild('a')
