const body=document.querySelector('body')
const div=document.querySelector('div')
body.appendChild(div)
const button=document.createElement('button')
div.appendChild(button)
const a=document.createElement('a')
button.appendChild(a)
a.setAttribute("href","index.html")
const text=document.createTextNode('Jouer')
a.appendChild(text)
